/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VesselCall {
  /**
   * UUID v4
   */
  id: string;
  vessel: {
    imo: number;
    name: string;
    type: "CONTAINER" | "RORO" | "BULK" | "TANKER" | "OTHER";
    loa_m: number;
    beam_m: number;
    draft_m: number;
    eta: string;
  };
  optimizerPlan: BerthPlan;
  aiPrediction?: {
    modelVersion: string;
    willChange: boolean;
    confidence?: number;
    suggestedPlan?: BerthPlan;
  };
  humanPlan?: BerthPlan;
  actualExecution?: {
    berthId: string;
    ata: string;
    atd: string;
  };
}
export interface BerthPlan {
  berthId: string;
  start: string;
  end: string;
}

export interface PlanItem {
  vesselId: number;
  startTime: string;
  endTime: string;
  berthId: number;
  actualStartTime: string;
  actualEndTime: string;
}

export interface Plan {
  schedule: PlanItem[];
}