"""Add fields for VesselCall schema

Revision ID: 468f90d9807c
Revises: 5e7036cdf271
Create Date: 2025-05-17 09:44:31.757587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468f90d9807c'
down_revision: Union[str, None] = '5e7036cdf271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessel_calls', sa.Column('vessel_name', sa.String(length=64), nullable=True))
    op.add_column('vessel_calls', sa.Column('vessel_type', sa.String(length=16), nullable=True))
    op.add_column('vessel_calls', sa.Column('loa_m', sa.Float(), nullable=True))
    op.add_column('vessel_calls', sa.Column('beam_m', sa.Float(), nullable=True))
    op.add_column('vessel_calls', sa.Column('draft_m', sa.Float(), nullable=True))
    op.add_column('vessel_calls', sa.Column('optimizer_berth_id', sa.String(), nullable=True))
    op.add_column('vessel_calls', sa.Column('optimizer_start', sa.DateTime(), nullable=True))
    op.add_column('vessel_calls', sa.Column('optimizer_end', sa.DateTime(), nullable=True))
    op.add_column('vessel_calls', sa.Column('ai_model_version', sa.String(), nullable=True))
    op.add_column('vessel_calls', sa.Column('ai_will_change', sa.Boolean(), nullable=True))
    op.add_column('vessel_calls', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('vessel_calls', sa.Column('ai_suggested_berth_id', sa.String(), nullable=True))
    op.add_column('vessel_calls', sa.Column('ai_suggested_start', sa.DateTime(), nullable=True))
    op.add_column('vessel_calls', sa.Column('ai_suggested_end', sa.DateTime(), nullable=True))
    op.add_column('vessel_calls', sa.Column('human_berth_id', sa.String(), nullable=True))
    op.add_column('vessel_calls', sa.Column('human_start', sa.DateTime(), nullable=True))
    op.add_column('vessel_calls', sa.Column('human_end', sa.DateTime(), nullable=True))
    op.add_column('vessel_calls', sa.Column('actual_berth_id', sa.String(), nullable=True))
    op.add_column('vessel_calls', sa.Column('ata', sa.DateTime(), nullable=True))
    op.add_column('vessel_calls', sa.Column('atd', sa.DateTime(), nullable=True))
    op.alter_column(
        'vessel_calls',
        'imo',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using="imo::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vessel_calls', 'imo',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('vessel_calls', 'atd')
    op.drop_column('vessel_calls', 'ata')
    op.drop_column('vessel_calls', 'actual_berth_id')
    op.drop_column('vessel_calls', 'human_end')
    op.drop_column('vessel_calls', 'human_start')
    op.drop_column('vessel_calls', 'human_berth_id')
    op.drop_column('vessel_calls', 'ai_suggested_end')
    op.drop_column('vessel_calls', 'ai_suggested_start')
    op.drop_column('vessel_calls', 'ai_suggested_berth_id')
    op.drop_column('vessel_calls', 'ai_confidence')
    op.drop_column('vessel_calls', 'ai_will_change')
    op.drop_column('vessel_calls', 'ai_model_version')
    op.drop_column('vessel_calls', 'optimizer_end')
    op.drop_column('vessel_calls', 'optimizer_start')
    op.drop_column('vessel_calls', 'optimizer_berth_id')
    op.drop_column('vessel_calls', 'draft_m')
    op.drop_column('vessel_calls', 'beam_m')
    op.drop_column('vessel_calls', 'loa_m')
    op.drop_column('vessel_calls', 'vessel_type')
    op.drop_column('vessel_calls', 'vessel_name')
    # ### end Alembic commands ###
