"""Initial schema

Revision ID: 5e7036cdf271
Revises: 
Create Date: 2025-05-17 09:25:28.004829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7036cdf271'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vessel_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imo', sa.String(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('etd', sa.DateTime(), nullable=False),
    sa.Column('planned_berth', sa.String(), nullable=True),
    sa.Column('human_override', sa.String(), nullable=True),
    sa.Column('actual_berth', sa.String(), nullable=True),
    sa.Column('predicted_change', sa.Boolean(), nullable=True),
    sa.Column('prediction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_calls_imo'), 'vessel_calls', ['imo'], unique=False)
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_call_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('will_change', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['vessel_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_vessel_calls_imo'), table_name='vessel_calls')
    op.drop_table('vessel_calls')
    op.drop_table('berths')
    # ### end Alembic commands ###
