"""Add berth constraints and vessel maintenance_id

Revision ID: 91b0325ab4f4
Revises: a60c96859c6d
Create Date: 2025-05-17 16:49:46.393435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b0325ab4f4'
down_revision: Union[str, None] = 'a60c96859c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('berths', sa.Column('max_loa', sa.Float(), nullable=True))
    op.add_column('berths', sa.Column('max_beam', sa.Float(), nullable=True))
    op.add_column('berths', sa.Column('max_draft', sa.Float(), nullable=True))
    op.add_column('berths', sa.Column('max_dwt', sa.Float(), nullable=True))
    op.add_column('berths', sa.Column('allowed_types', sa.String(), nullable=True))
    op.add_column('berths', sa.Column('maintenance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'berths', 'maintenance_logs', ['maintenance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'berths', type_='foreignkey')
    op.drop_column('berths', 'maintenance_id')
    op.drop_column('berths', 'allowed_types')
    op.drop_column('berths', 'max_dwt')
    op.drop_column('berths', 'max_draft')
    op.drop_column('berths', 'max_beam')
    op.drop_column('berths', 'max_loa')
    # ### end Alembic commands ###
