"""Add maintenance log

Revision ID: a60c96859c6d
Revises: 59b08915726f
Create Date: 2025-05-17 13:33:05.489159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60c96859c6d'
down_revision: Union[str, None] = '59b08915726f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessel_calls', sa.Column('aba', sa.DateTime(), nullable=True))
    op.add_column('vessel_calls', sa.Column('weather_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vessel_calls', 'weather', ['weather_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vessel_calls', type_='foreignkey')
    op.drop_column('vessel_calls', 'weather_id')
    op.drop_column('vessel_calls', 'aba')
    # ### end Alembic commands ###
