"""Initial

Revision ID: ba2754255513
Revises: 
Create Date: 2025-05-17 23:10:34.934542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2754255513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('max_loa', sa.Float(), nullable=True),
    sa.Column('max_beam', sa.Float(), nullable=True),
    sa.Column('max_draft', sa.Float(), nullable=True),
    sa.Column('max_dwt', sa.Float(), nullable=True),
    sa.Column('allowed_types', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actual_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('loa_m', sa.Float(), nullable=True),
    sa.Column('beam_m', sa.Float(), nullable=True),
    sa.Column('draft_m', sa.Float(), nullable=True),
    sa.Column('dwt_t', sa.Float(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('ebt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('wind_speed_knots', sa.Float(), nullable=True),
    sa.Column('tide_height_m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_timestamp'), 'weather', ['timestamp'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('berth_name', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['berth_name'], ['berths.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_call_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('will_change', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_call_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('berth_id', sa.Integer(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel_schedule_entries')
    op.drop_table('prediction_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_weather_timestamp'), table_name='weather')
    op.drop_table('weather')
    op.drop_table('vessels')
    op.drop_table('users')
    op.drop_table('berths')
    # ### end Alembic commands ###
